NProject.Web/ViewModels/Project/Shared.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NProject.Web.ViewModels.Project
{
    public class Shared
    {
        public List<NProject.Models.Domain.Project> Projects { get; set; }

    }
}

NProject.Web/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.ServiceLocation;
using NProject.Models.Domain;
using NProject.Web.Helpers;

namespace NProject.Web.Controllers
{
    public class MessageController : BaseController
    {
        //
        // GET: /Message/

        public ActionResult Index()
        {
            var data = ServiceLocator.Current.GetInstance<INProjectEntities>();
            var messages = data.Invitations.Where(i => i.Invitee.Id == SessionStorage.User.Id).ToList();

            return View(messages.ToList());
        }

    }
}

NProject.Web/Controllers/WorkspaceController.cs
using System.Web.Mvc;
using NProject.BLL;
using NProject.Models.Domain;
using NProject.Web.Helpers;
using NProject.Web.ViewModels.Workspace;

namespace NProject.Web.Controllers
{
    [Authorize]
    [HandleError]
    public class WorkspaceController : BaseController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            ViewBag.ActiveMenu = "workspaces";
        }
        //
        // GET: /Workspace/
        //Show list of all user's workspaces
        [Authorize]
        public ActionResult Index()
        {
            var cs = new WorkspaceService();
            int userId = SessionStorage.User.Id;
           // int workspaceId = cs.GetDefaultWorkspaceForUser(userId);

            return View(cs.GetWorkspacesForUser(userId));
        }

        [Authorize]
        public ActionResult Create()
        {
            //TODO: Check for user account type, if it is free or not
            return View(new Form {Workspace = new Workspace()});
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(Form form)
        {
            if (!ModelState.IsValid) return View(form);

            form.Workspace.Owner = new UserService().GetUser(SessionStorage.User.Id);
            new WorkspaceService().AddWorkspace(form.Workspace);

            //TODO: Check for user account type, if it is free or not
            return RedirectToAction("Index");
        }

        public ActionResult Show(int id)
        {
            var ws = new WorkspaceService();
            var workspace = ws.GetWorkspace(id);
            if (workspace != null && ws.IsUserCanInteractWithWorkspace(SessionStorage.User.Id, id))
                return View(workspace);

            this.SetTempMessage("You can't see this page.", "error");
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var ws = new WorkspaceService();
            var workspace = ws.GetWorkspace(id);
            if (workspace != null && ws.IsUserCanInteractWithWorkspace(SessionStorage.User.Id, id))
                return View(new Form() {Workspace = workspace, IsEditing = true});

            this.SetTempMessage("You can't see this page.", "error");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Form form)
        {
            var ws = new WorkspaceService();
            if (ws.IsUserCanInteractWithWorkspace(SessionStorage.User.Id, form.Workspace.Id))
            {
                ws.UpdateWorkspace(form.Workspace);
                this.SetTempMessage("Workspace has been updated.", "success");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var ws = new WorkspaceService();
            if (ws.IsUserCanInteractWithWorkspace(SessionStorage.User.Id, id))
            {
                ws.DeleteWorkspace(id);
                this.SetTempMessage("Workspace has been deleted.", "success");
            }
            return RedirectToAction("Index");
        }
    }
}

NProject.Web/Views/Shared/Site.Layout.cshtml
@using NProject.Web.Helpers

@helper DisplayMenu()
{
    if (User.Identity.IsAuthenticated)
    {
        <ul class="nav">
        <li @if (ViewBag.ActiveMenu == "workspaces") {  @("class=active")}><a href="@Url.Action("Index", "Workspace")">My Workspaces</a></li>
            <li><a href="@Url.Action("Shared", "Project")">Shared projects</a></li>
            <li><a href="@Url.Action("Index", "Message")">My messages</a></li>
        </ul>
        <div class="pull-right">
            @Html.ActionLink(SessionStorage.User.UserName, "Settings", "Home")
            @Html.ActionLink("Sign out", "Logoff", "Account", new { }, new { @class="btn" })
        </div>
    }
    else
    {
        <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>

        using (Html.BeginForm("Logon", "Account", FormMethod.Post, new {@class = "navbar-search pull-right"}))
        {
            <input type="hidden" name="returnUrl" value="@Request["returnUrl"]" />
            <input class="input-small" type="text" placeholder="E-mail" name="email" value=""/>
            <input class="input-small" type="password" placeholder="Password" name="password" value=""/>

            <button type="submit" class="btn" style="margin-top: -9px">Sign in</button>
        }
    }
}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>@ViewBag.Title | NProject</title>
    <meta name="description" content="NProject"/>
    <meta name="author" content="Ivan Manzhos"/>

    <!-- HTML5 library for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Styles -->
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap.min.css")"/>
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript" language="javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript" language="javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript" language="javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.globalize.js")" type="text/javascript" language="javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.globalize.culture.ru-RU.js")" type="text/javascript" language="javascript"></script>
    @RenderSection("JSScript", false)

    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom:40px;
      }
    </style>

    <script type="text/javascript">
        $.validator.methods.number = function(value, element) {
            return !isNaN(Globalize.parseFloat(value));
        };
        $(document).ready(function () {
            Globalize.culture('ru-RU');
            
            
            
            @RenderSection("DocumentReadyJS", false)
            
          //  $.culture = Globalize.cultures["ru-RU"];
            //$.preferCulture($.culture.name);
        });
</script>

   @* <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">*@
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="@Url.Action("Index", "Home")">NProject</a>
            @DisplayMenu()
        </div>
      </div>
    </div>
    <div class="container">
    @RenderSection("Breadcrumbs", false)

    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-error">
            <p>@TempData["ErrorMessage"]</p>
        </div>
    }
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            <p>@TempData["SuccessMessage"]</p>
        </div>
    }
    @RenderBody()
      <!-- Example row of columns -->
@*      <div class="row">
        <div class="span6">
          <h2>Heading</h2>
          <p>Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span5">
          <h2>Heading</h2>
           <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
      </div>

      
      *@<div style="clear:both"></div>
      <footer>
      <div style="text-align:center">
        <p>&copy; Ivan Manzhos 2012</p>
       </div>
      </footer>
    </div> <!-- /container -->

  </body>
</html>