NProject.Web/ViewModels/Meeting/Create.cs
using System.Linq;
using System.Collections.Generic;
using NProject.Models.Domain;

namespace NProject.Web.ViewModels.Meeting
{
    public class Form : ViewModelBase
    {
        public NProject.Models.Domain.Meeting Meeting { get; set; }
        public IEnumerable<TeamMate> Team { get; set; }
        public string TeamParticipants { get; set; }
        public string OtherParticipants { get; set; }

        public string TeamDataSource
        {
            get { return string.Format("[{0}]", string.Join(",", Team.Select(t => string.Format("\"{0}\"", t.User.Name)))); }
        }
    }
}

NProject.Web/ViewModels/Meeting/List.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NProject.Web.ViewModels.Meeting
{
    public class List : ViewModelBase
    {
        public IEnumerable<NProject.Models.Domain.Meeting> Meetings { get; set; }

        public bool CanUserEditMeetings { get; set; }

        public string MeetingFilter { get; set; }
    }
}

NProject.Web/ViewModels/Meeting/Show.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NProject.Web.ViewModels.Meeting
{
    public class Show : ViewModelBase
    {
        public NProject.Models.Domain.Meeting Meeting { get; set; }

        public bool HasNotYetStarted { get { return (Meeting.EventDate - DateTime.UtcNow).TotalMinutes > 5; } }
        //public bool IsMeetingPassed{get{ return Meeting.EventDate < }}
    }
}

NProject.Web/ViewModels/Project/CreateForm.cs
using System.ComponentModel.DataAnnotations;

namespace NProject.Web.ViewModels.Project
{
    public class CreateForm
    {
        [Required, StringLength(100)]
        public string Name { get; set; }

        public string Description { get; set; }

        [Required]
        public int WorkspaceId { get; set; }
    }
}

NProject.Web/ViewModels/Task/List.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using NProject.Models.Domain;

namespace NProject.Web.ViewModels.Task
{
    public class List : ViewModelBase
    {
        public IEnumerable<NProject.Models.Domain.Task> Tasks { get; set; }
        public bool CanUserEditTasks { get; set; }

        public string TaskFilter { get; set; }
    }
}

NProject.Web/ViewModels/Task/Show.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NProject.Web.ViewModels.Task
{
    public class Show : ViewModelBase
    {
        public NProject.Models.Domain.Task Task { get; set; }
        public bool CanUserAcceptTask { get; set; }
        public bool AssignedForCurrentUser { get; set; }
    }
}

NProject.Web/Controllers/MeetingController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using NProject.BLL;
using NProject.Web.Helpers;
using NProject.Web.ViewModels.Meeting;

namespace NProject.Web.Controllers
{
    [HandleError]
    [Authorize]
    public class MeetingController : BaseController
    {
        private ProjectService ps = new ProjectService();


        public ActionResult List(int id, string show = "future")
        {
            var project = ps.GetProjectById(id);
            List l = new List
                         {
                             Meetings = ps.GetMeetings(id, show),
                             ProjectId = id,
                             ProjectName = project.Name,
                             CanUserEditMeetings = project.Team.Any(
                                 t =>
                                 t.AccessLevel == Models.Domain.AccessLevel.ProjectManager &&
                                 t.UserId == SessionStorage.User.Id),
                             MeetingFilter = show
                         };

            return View(l);
        }

        public ActionResult Create(int id)
        {    
            var team = ps.GetProjectTeam(id);

            var meeting = new Models.Domain.Meeting();
            meeting.EventDate = meeting.EventDate.AddHours(SessionStorage.User.HoursOffsetFromUtc);
            meeting.ProjectId = id;
            

            return View(new Form {ProjectId = id, Team = team, Meeting = meeting});
        }

        [HttpPost]
        public ActionResult Create(Form model)
        {
            model.Meeting.OrganizerId = SessionStorage.User.Id;
            ps.AddMeeting(model.Meeting, model.TeamParticipants, model.OtherParticipants);
            
            return RedirectToAction("Show", "Project", new {model.Meeting.ProjectId});
        }

        public ActionResult Edit(int id)
        {
            var meeting = ps.GetMeeting(id);
            meeting.EventDate = meeting.EventDate.AddHours(SessionStorage.User.HoursOffsetFromUtc);
     

            var team = ps.GetProjectTeam(meeting.ProjectId);
            var model = new Form
                            {
                                ProjectId = id,
                                Team = team,
                                Meeting = meeting,
                                TeamParticipants = string.Join(" ",
                                                               meeting.Participants.Where(
                                                                   p => meeting.Project.Team.Any(t => t.UserId == p.Id))
                                                                   .Select(
                                                                       p => p.Id)),
                                OtherParticipants =
                                    string.Join(" ",
                                                meeting.Participants.Where(
                                                    p => !meeting.Project.Team.Any(t => t.UserId == p.Id)).Select(
                                                        p => p.Email))
                            };

            return View("Create", model);
        }
        [HttpPost]
        public ActionResult Edit(Form model)
        {
            //set time to UTC
            model.Meeting.EventDate = model.Meeting.EventDate.AddHours(-SessionStorage.User.HoursOffsetFromUtc);

            ps.UpdateMeeting(model.Meeting, model.TeamParticipants, model.OtherParticipants);

            return RedirectToAction("List", new {id = model.Meeting.ProjectId});
        }

        public ActionResult Show(int id, string accessToken = "")
        {
            var meeting = ps.GetMeeting(id);

            var model = new Show()
                            {Meeting = meeting, ProjectId = meeting.ProjectId, ProjectName = meeting.Project.Name};
            return View(model);
        }

        [HttpPost]
        public ActionResult PostComment(int id, string message)
        {
            ps.PostComment(id, message, SessionStorage.User.Id);

            return RedirectToAction("Show", new {id});
        }

        [HttpPost]
        public ActionResult FinishMeeting(int id)
        {
            var m = ps.FinishMeeting(id);

            return RedirectToAction("List", new {id = m.ProjectId});
        }
    }
}

NProject.Web/Views/Meeting/Create.cshtml
@model NProject.Web.ViewModels.Meeting.Form
@{
    ViewBag.Title = "Create";
}
@section JSScript
{
    <script src="@Url.Content("~/Scripts/bootstrap-typeahead.js")" type="text/javascript" language="javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datepicker.js")" type="text/javascript" language="javascript"></script>
}
@section DocumentReadyJS
{
$.validator.methods.date = function(value, element) { return Globalize.parseDate(value); };
$('#tbDatePicker').val(Globalize.format('@Model.Meeting.EventDate.ToShortDateString()', 'd')).datepicker({monthNames:Globalize.culture().calendar.months.names,shortDayNames:
Globalize.culture().calendar.days.namesShort});

$('#meetingTime').val(Globalize.format('@Model.Meeting.EventDate.ToShortTimeString()', 't'));
parseMeetingParticipants();
}
<h2>
    New meeting</h2>
<div class="alert alert-info">
    Meeting is a way to get user feedback, discuss some topics or order your development process.
</div>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(m => m.Meeting.ProjectId)
    @Html.HiddenFor(model => model.Meeting.OrganizerId)
    @Html.HiddenFor(model => model.TeamParticipants, new { id = "teamParticipants" })
    @Html.HiddenFor(model => model.OtherParticipants, new { id = "otherParticipants" })
    @Html.HiddenFor(model => model.Meeting.Id)
    <fieldset>
        <legend></legend>
        <div style="padding-top: 5px; border-bottom: 1px solid #EEE;">
            <input type="submit" class="btn btn-small btn-primary" value="Save" />
            @*            <div class="pull-right">
                <a class="btn btn-danger btn-small" href="#delete_task_modal" data-toggle="modal"><i
                    class="icon-trash"></i>Delete </a>
            </div>*@
        </div>
        <div style="float: left">
            <div class="control-group">
                @Html.LabelFor(model => model.Meeting.Name)
                <div class="controls">
                    @Html.TextBoxFor(model => model.Meeting.Name, new { @class = "span9" })
                    @Html.ValidationMessageFor(model => model.Meeting.Name)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(model => model.Meeting.EventDate, new { style = "float: left;padding: 5px 5px 0 0" })
                <div class="controls" style="float: left">
                    @Html.TextBoxFor(model => model.Meeting.EventDate, new { data_val_date = "Wrong format!", id = "tbDatePicker", @class = "span2", data_val_eventLaterNow = "It can be today or on next days." })
                    @Html.ValidationMessageFor(model => model.Meeting.EventDate)
                </div>
            </div>
            <div class="control-group" style="float: left; margin-left: 10px">
                <label for="" style="float: left; padding: 5px 5px 0 0">Time</label>
                <div class="controls" style="float: left">
                    <input type="text" class="span1" id="meetingTime" name="meetingTime" data-val-eventLaterNow="You can't create it in the past" data-val="true" data-val-date="Time record" />
                    <span class="field-validation-error" data-valmsg-for="meetingTime" data-valmsg-replace="true">
                    </span>
                </div>
            </div>
            <div class="control-group" style="clear: both">
                @Html.LabelFor(model => model.Meeting.Description)
            
            <div class="controls">
                @Html.TextAreaFor(model => model.Meeting.Description, new { @class = "span9", rows = 6 })
                @Html.ValidationMessageFor(model => model.Meeting.Description)
            </div>
            </div>
        </div>
        <div style="margin-left: 20px; float: left">
            <div class="control-group">
                @Html.LabelFor(model => model.Meeting.Participants)
                <div class="controls">
                    <input type="text" class="span3" data-provide="typeahead" name="tbUserList" id="tbUserList"
                        placeholder="Type user names or emails..." data-val="true" data-val-checkparticipants="Add at least one participant"
                        data-items="4" data-source="@Model.TeamDataSource">
                    <span class="field-validation-error" data-valmsg-for="tbUserList" data-valmsg-replace="true">
                    </span>
                </div>
            </div>
            <div style="margin-top: 10px" id="selectedUsers" />
        </div>
    </fieldset>
}
<script language="javascript" type="text/javascript">
    $("#tbUserList").on('selected.typeahead enterPressed.typeahead', function(event, value) {
        if (team[value] !== undefined) {
            if (!team[value].selected) {
                team[value].selected = true;
                appendAndClear(value);
            }
        }
        else {
            if (additionalPeople[value] === undefined) {
                additionalPeople[value] = 1;
                appendAndClear(value);
            }
        }
    });

    function appendAndClear(value) {
        $('#selectedUsers').append('<div class="alert alert-success" style="margin-bottom: 5px">' +
            '<a class="close" onclick="deleteParticipant(this)">×</a>' + value + '</div>');
        $('#tbUserList').focus().val(''); //clear selected value 
        participantsCount++;
        $('#tbUserList').parent().parent().removeClass('error');
    }
    
    function deleteParticipant(sender) {
        var loggedUser = '@SessionStorage.User.UserName';
        var value = $(sender).parent().text().substring(1, 100);
        
        if(loggedUser == value) {
            alert("You can't remove yourself from a meeting");
            return;
        }
        if (team[value] !== undefined)
            team[value] = false;
        else
            delete additionalPeople[value];

        participantsCount--;
        
        $(sender).parent().remove(); //remove box in UI
    }

    var team = new Object();
    @foreach (var user in Model.Team)
    {
        if(user.UserId == SessionStorage.User.Id)
        {
            @:appendAndClear('@user.User.Name');
            @:team['@user.User.Name'] = {id:@user.UserId, selected: true};
        }
        else
        {
            @:team['@user.User.Name'] = {id:@user.UserId, selected: false};
        }
    }
    var additionalPeople = new Object();
    var participantsCount = 0;
    //prevent page submit by enter pressing
    $('#tbUserList').on('keydown keypress keyup', function(e) {
        if(e.keyCode == 13) {
            e.preventDefault();
        }
    });
    $(window).keypress(function(e) {
        if (e.keyCode == 13) e.preventDefault();
    });
    //we have to set some fields manually
    $('form').submit(function(e) {
        $(this).validate();
        if (!$(this).valid()) return false;

        //update date
        var date = Globalize.parseDate($('#tbDatePicker').val());
        var time = Globalize.parseDate($('#meetingTime').val());
        date.setHours(time.getHours());
        date.setMinutes(time.getMinutes());
        $('#tbDatePicker').val(Globalize.format(date, 'F'));

        //create list of team
        var teamString = '';
        for(var user in team) {
            if (team[user].selected)
                teamString += team[user].id + ' ';
        }
        $('#teamParticipants').val(teamString);
        
        //create list of team
        var otherPartString = '';
        for(var user in additionalPeople)
                otherPartString += user + ' ';
        $('#otherParticipants').val(otherPartString);
    });
        $.validator.addMethod('checkParticipants', function(value, element) {
            // 'value' is the value of the control being validated.
            return participantsCount > 0; // Return true or false depending on if it passes or fails validation, respectively.
        }, 'Html not allowed');
     $.validator.unobtrusive.adapters.addBool('checkParticipants');
     
     $.validator.addMethod('eventLaterNow', function(value, element) {
         var currentDate = new Date();
         var date = Globalize.parseDate($('#tbDatePicker').val());
         if(element.name == 'meetingTime')
         {
             //if we check date + time, we should have date only bigger than current
             var time = Globalize.parseDate($('#meetingTime').val());
             date.setHours(time.getHours());
             date.setMinutes(time.getMinutes());

             return date > currentDate;
         }
         else
         {
             //we check just date, so it can be today
             currentDate.setHours(0);
             currentDate.setMinutes(0);
             currentDate.setSeconds(0);
             currentDate.setMilliseconds(0);
             
             return date >= currentDate;
         }
     }, 'asd');
     $.validator.unobtrusive.adapters.addBool('eventLaterNow');
     function parseMeetingParticipants() {
         var teamParticipants = '@Model.TeamParticipants'.split(" ");
         var otherParticipants = '@Model.OtherParticipants'.split(" ");

         for (var i = 0; i < teamParticipants.length; i++)
             if(teamParticipants[i] != '')
                    for(var user in team) 
                        if (team[user].id == teamParticipants[i]) {
                            team[user].selected=true;
                            appendAndClear(user);
                        }
         for (var i = 0; i < otherParticipants.length; i++) {
             if (otherParticipants[i] != '') {
                 additionalPeople[otherParticipants[i]] = 1;
                 appendAndClear(otherParticipants[i]);
             }
         }
     }
</script>

NProject.Web/Views/Meeting/List.cshtml
@model NProject.Web.ViewModels.Meeting.List

@{
    ViewBag.Title = "List";
}
@section Breadcrumbs
{
    @RazorHelpers.RenderBreadcrumbs(new Dictionary<string, string> { { Url.Action("Show", "Project", new {id = Model.ProjectId }), Model.ProjectName },
                                                                     {"", "Meetings"} })
}
<h2>Project's meetings</h2>
     <div class="row" style="margin-bottom: 5px;">
     <div style="display: inline; margin-left:20px" class="controls">
     Show: 
     <select onchange="javascript:document.location.search = 'show='+this.value" id="taskFilter">
        <option value="all">All meetings</option>
        <option value="past">Past</option>
        <option value="future" selected="selected">Future</option>
     </select>
     </div>
     @if (Model.CanUserEditMeetings)
     {
         <div class="pull-right">
             <a class="btn btn-success btn-small" href="@Url.Action("Create", "Meeting", new {id = Model.ProjectId})">
                 <i class="icon-plus"></i> Create new
             </a>
         </div>
     }
     </div>
 
<table  class="table table-striped">
    <tr>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            Begin date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Meetings)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @RazorHelpers.ConvertUtcToUserTime(item.EventDate)
        </td>
        <td>
            @Html.ActionLink("Show", "Show", new {id = item.Id})
            @if (Model.CanUserEditMeetings && !item.Finished)
            {
                @:| @Html.ActionLink("Edit", "Edit", new {id = item.Id})
            }
        </td>
    </tr>
}

</table>
<script type="text/javascript">
    document.getElementById('taskFilter').value = '@Model.MeetingFilter';
</script>

NProject.Web/Views/Meeting/Show.cshtml
@model NProject.Web.ViewModels.Meeting.Show
@{
    ViewBag.Title = "Show meeting";
}
@section Breadcrumbs
{
    @RazorHelpers.RenderBreadcrumbs(new Dictionary<string, string> { { Url.Action("Show", "Project", new {id = Model.ProjectId }), Model.ProjectName },
                                                                     {Url.Action("List", "Meeting", new {id=Model.ProjectId}), "Meetings"},
                                                                     {"", Model.Meeting.Name},
})
}
<div class="page-header">
    <h1>@Model.Meeting.Name <small>@RazorHelpers.GetUserDateTimeByUtc(Model.Meeting.EventDate).ToString("f")</small></h1>
</div>
@if (!Model.Meeting.Finished && !Model.HasNotYetStarted && Model.Meeting.OrganizerId == SessionStorage.User.Id)
{
    <div class="buttons-row">
    @using (Html.BeginForm("FinishMeeting", "Meeting"))
    {
        @Html.Hidden("id", Model.Meeting.Id)
        <input type="submit" class="btn btn-small btn-primary" value="Finish meeting" />
            @*            <div class="pull-right">
                <a class="btn btn-danger btn-small" href="#delete_task_modal" data-toggle="modal"><i
                    class="icon-trash"></i>Delete </a>
            </div>*@
    }
        </div>
}
<div style="float: left">
    <h4>
        Description</h4>
    <div class="well" style="margin: 10px 0 0 0; width: 660px">
        @Model.Meeting.Description
    </div>
    @if (Model.HasNotYetStarted)
    {
        <div class="alert" style="margin-top: 15px">
            <strong>No history.</strong> This meeting will be started on @RazorHelpers.ConvertUtcToUserTime(Model.Meeting.EventDate)</div>
    }
    else if (Model.Meeting.Finished)
    {
        <div class="alert" style="margin-top: 15px">
            <strong>Finished.</strong> This meeting  has been already finished.</div>
    }
    else
    {
        <div id="commentForm">
            @using (Html.BeginForm("PostComment", "Meeting", new { id = Model.Meeting.Id }, FormMethod.Post))
            {
                <fieldset>
                    <legend>History</legend>
                    <div class="control-group" style="margin-top: 5px">
                        <div class="controls">
                            @Html.TextArea("message", new { @class = "span8", rows = 2, style = "margin-top:5px", data_val = "true", data_val_required = "The Message field is required." })
                            @Html.ValidationMessage("message")
                        </div>
                    </div>
                    <input type="submit" class="btn btn-primary" value="Post" />
                </fieldset>
            }
        </div>
    }
    <div id="comments">
        @foreach (var cm in Model.Meeting.MeetingComments)
        {
            <div style="border: 1px #eee solid; padding: 5px; margin: 5px 0;">
                <strong>@cm.Author.Name</strong> at @RazorHelpers.ConvertUtcToUserTime(cm.CreationDate)<br />
                @cm.Text
            </div>
        }
    </div>
</div>
<div style="float: left" class="span3">
    <h4 style="text-align: center">
        Participants</h4>
    <div style="margin-top: 10px" id="selectedUsers">
        @foreach (var user in Model.Meeting.Participants)
        {
            <div class="alert alert-success" style="margin-bottom: 5px">
                @if (user.Id == Model.Meeting.OrganizerId)
                {
                    <i class="icon-bookmark"></i>
                }
                @user.Name
            </div>
        }
    </div>
</div>
<div style="clear: both">
</div>